"""add_plan_and_usage_models

Revision ID: 2
Revises: 1
Create Date: 2024-07-29 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2'
down_revision: Union[str, None] = '1' # This migration comes after revision '1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'plan' and 'subscription_status' columns to 'users' table
    op.add_column('users', sa.Column('plan', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('subscription_status', sa.String(), server_default='active', nullable=False))

    # Create 'usage' table
    op.create_table('usage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('words_scanned', sa.Integer(), server_default='0', nullable=False),
        sa.Column('humanizer_uses', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_reset', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_usage_id'), 'usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop 'usage' table
    op.drop_index(op.f('ix_usage_id'), table_name='usage')
    op.drop_table('usage')

    # Drop columns from 'users' table
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
